services:
  db:
    image: postgres:16
    container_name: event_platform_db
    environment:
      POSTGRES_DB: event_platform
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1235
    ports:
      - "5433:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

volumes:
  postgres_data: